spring:
  cloud:
    function:
      definition: holidayFunction
  main:
    web-application-type: none
  docker:
    compose:
      lifecycle-management: start-only

aws:
  endpoint: http://localhost:4566
  region: us-east-1
  dynamodb:
    table-name: holidays
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
