spring:
  cloud:
    function:
      definition: holidayFunction
      scan:
        enabled: true
    function.web.export:
      enabled: true
  profiles:
    active: local
  main:
    web-application-type: servlet
  docker:
    compose:
      lifecycle-management: start-only

aws:
  endpoint: http://localhost:4566
  region: us-east-1
  dynamodb:
    table-name: holidays

server:
  port: 8080
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
